#!/bin/bash

set -e

write_cache()
{
if [ -x /usr/bin/gtk-update-icon-cache ]; then
    if ! gtk-update-icon-cache --force --quiet /usr/share/icons/Trenta; then
        echo "WARNING: icon cache generation failed"
    fi
fi
}

if [ "$1" = "triggered" ]; then
    write_cache
    exit
fi

write_cache

bash /usr/share/icons/Trenta/fix.sh
bash /usr/share/icons/Trenta/hide-icon.sh /usr/share/icons/Trenta/garbage.txt

exit 0
